### ISSUE TITLE
Missing symbols running under electron

### ISSUE THREAD

**Issue by 2fours** [PeculiarVentures/node-webcrypto-ossl#102]
I get this error when requiring node-webcrypto-ssl in an html file under electron: 

Uncaught Error: dlopen(/Users/adam/dev/surespot-desktop/node_modules/node-webcrypto-ossl/build/Release/nodessl.node, 1): Symbol not found: _EVP_PKEY_decrypt
  Referenced from: /Users/adam/dev/surespot-desktop/node_modules/node-webcrypto-ossl/build/Release/nodessl.node
  Expected in: flat namespace
 in /Users/adam/dev/surespot-desktop/node_modules/node-webcrypto-ossl/build/Release/nodessl.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/adam/dev/surespot-desktop/node_modules/node-webcrypto-ossl/buildjs/native.js:3:14)
    at Object.<anonymous> (/Users/adam/dev/surespot-desktop/node_modules/node-webcrypto-ossl/buildjs/native.js:6:3)

**Comment by 2fours** [comment]
Related to this? https://github.com/electron/electron/issues/9275

**Comment by 2fours** [comment]
Also https://electron.atom.io/blog/2016/08/08/electron-internals-using-node-as-a-library

**Comment by 2fours** [comment]
Just found this: https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/77...so is electron not supported?

**Comment by 2fours** [comment]
I managed to get it working by modifying the bindings.gyp to use the include files and static lib for the homebrew openssl implementation on my machine. It would seem that in order to work cross platform for electron that node-webcrypto-ossl should probably build openssl as suggested in the above links.

**Comment by microshine** [comment]
You can use `.npmrc` file in you project. It allows to install `node-webcrypto-ossl` for electron.

__.npmrc__
```
target = 1.6.10
arch = x64
target_arch = x64
disturl=https://atom.io/download/electron
runtime = electron
build_from_source = true
openssl_dir = C:/openssl
```

**Comment by 2fours** [comment]
Thanks.
