### ISSUE TITLE
Node 4:  SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by MichaelJCole** [PeculiarVentures/node-webcrypto-ossl#130]
I'm getting this error on Node 4 using the npm package with Meteorjs 1.5:

```
W20180705-22:37:54.140(-7)? (STDERR) /home/michael/scm/infoworks/apricot-meteor/apricot/node_modules/node-webcrypto-ossl/buildjs/crypto/ec.js:38
W20180705-22:37:54.141(-7)? (STDERR) function buf_pad(buf, padSize = 0) {
W20180705-22:37:54.141(-7)? (STDERR)                               ^
W20180705-22:37:54.141(-7)? (STDERR) 
W20180705-22:37:54.142(-7)? (STDERR) SyntaxError: Unexpected token =
W20180705-22:37:54.142(-7)? (STDERR)     at exports.runInThisContext (vm.js:53:16)
W20180705-22:37:54.142(-7)? (STDERR)     at Module._compile (module.js:373:25)
W20180705-22:37:54.143(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20180705-22:37:54.143(-7)? (STDERR)     at Module.load (module.js:343:32)
W20180705-22:37:54.144(-7)? (STDERR)     at Function.Module._load (module.js:300:12)
W20180705-22:37:54.144(-7)? (STDERR)     at Module.require (module.js:353:17)
W20180705-22:37:54.144(-7)? (STDERR)     at require (internal/module.js:12:17)
W20180705-22:37:54.145(-7)? (STDERR)     at Object.<anonymous> (/home/michael/scm/infoworks/apricot-meteor/apricot/node_modules/node-webcrypto-ossl/buildjs/subtle.js:9:12)
W20180705-22:37:54.145(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20180705-22:37:54.146(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
```

**Comment by rmhrisk** [comment]
Node 4 is 4 years old and is not supported. This may not be the issue here but I strongly suspect if you upgrade to 8,9 or 10 it will work.

**Comment by microshine** [comment]
`function buf_pad(buf, padSize = 0)` is ES6
You need to update your nodejs to version which supports ES6

**Comment by MichaelJCole** [comment]
@rmhrisk @microshine Sure, maybe.  Also, I fixed it in my fork.  There was only one place where the default was used, so that seems like a bug to me.

Also, tsconfig.json was configured incorrectly for the targets in package.json.  Scaling it back to "es5" fixed the problem with the build.

I've tried the package with Node 4 and ecdsa and haven't found a problem yet.

**Comment by rmhrisk** [comment]
There are many CVEs in Node 4, you shouldn’t use a 4 year old platform, especially if your concerned with signing and encryption in the application.
