### ISSUE TITLE
Cannot read property 'decryptGcm' of undefined

### ISSUE THREAD

**Issue by amark** [PeculiarVentures/node-webcrypto-ossl#137]
I'm getting this error in my tests. Not sure if something is just wrong with the build on my local machine or if this is others.

The **same happens for `encryptGcm`.**

```
TypeError: Cannot read property 'decryptGcm' of undefined
    at EncryptDecrypt.Promise (/Users/mark/Dropbox/Public/gun/gun/node_modules/node-webcrypto-ossl/buildjs/crypto/aes.js:121:35)
    at new Promise (<anonymous>)
    at Function.EncryptDecrypt (/Users/mark/Dropbox/Public/gun/gun/node_modules/node-webcrypto-ossl/buildjs/crypto/aes.js:102:16)
    at Function.decrypt (/Users/mark/Dropbox/Public/gun/gun/node_modules/node-webcrypto-ossl/buildjs/crypto/aes.js:98:25)
    at decrypt.apply.then (/Users/mark/Dropbox/Public/gun/gun/node_modules/node-webcrypto-ossl/buildjs/subtle.js:187:29)
    at <anonymous>
(node:4006) UnhandledPromiseRejectionWarning: Error: expected undefined to equal 'hello self'
    at Assertion.assert (/Users/mark/Dropbox/Public/gun/gun/test/expect.js:96:13)
    at Assertion.be.Assertion.equal (/Users/mark/Dropbox/Public/gun/gun/test/expect.js:216:10)
    at Assertion.(anonymous function) [as be] (/Users/mark/Dropbox/Public/gun/gun/test/expect.js:69:24)
    at Context.<anonymous> (/Users/mark/Dropbox/Public/gun/gun/test/sea/sea.js:48:22)
    at <anonymous>
(node:4006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4006) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried to poke around in code ... often (of `undefined` just typo/missing something) but `.native` seems to go to C/C++ code.

Would be lovely to have a fix soon, because then I could drop a few other dependencies and only rely upon `ossl`! :D :) Great job & library, BTW.

**Comment by amark** [comment]
this was my fault. Works fine. Closing.

**Comment by anatolyg49** [comment]
@amark I have the same problem. What was the solution for you?

**Comment by amark** [comment]
I think I was passing wrong parameters, I forget tho, and we'ves witched to peculiar/webcrypto instead of the ossl bridge, I recommend you check their other library out instead.
